language: php

php:
  # see http://php.net/supported-versions.php
  - '7.0' # deprecated
  - '7.1' # Until 1 Dec 2019
  - '7.2' # Until 30 Nov 2020
  - '7.3' # Until 6 Dec 2021
node_js:
  - 12.13

addons:
  apt:
    packages:
      - parallel

env:
  global:
    - PHPUNIT_VERSION="~7|~8"
    - COMPOSER_CACHE_DIR=/home/travis/.composer
    - WP_VERSION="*"
    # All jobs shall share the composer cache
    - CACHE_NAME=$TRAVIS_BRANCH
  matrix:
    # see https://codex.wordpress.org/WordPress_Versions
    # see https://phpunit.de/supported-versions.html
    - WP_VERSION=5.2.4
    # - WP_VERSION=5.1.*
    # - WP_VERSION=5.0.*
    # - WP_VERSION=4.9.*
    # - WP_VERSION=4.8.*

matrix:
  include: # testing upcoming support
    - php: '7.4snapshot'
      env: PHPUNIT_VERSION=~8 WP_VERSION=5.2.4
    - php: 'nightly'
      env: PHPUNIT_VERSION=~8 WP_VERSION=5.2.4

  allow_failures: # for upcoming support or to check for deprecations
    - php: '5.6'
    - php: '7.0'
    - php: '7.4snapshot'
    - php: 'nightly'
  # Do not wait for allowed failures
  fast_finish: true

services:
  - mysql

cache:
  directories:
    - $HOME/.composer
    - $HOME/wordpress-develop/node_modules

# Setup environment and gather all needed files
before_install:
  - mysql -e 'CREATE DATABASE dev;'
  # Check WordPress unit tests
  # see https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/
  - git clone --branch=$WP_VERSION --depth=1 git://develop.git.wordpress.org/ wordpress-develop
  - wget https://phar.phpunit.de/phpunit-7.5.9.phar
  - chmod +x phpunit-7.5.9.phar
  - mv phpunit-7.5.9.phar wordpress-develop/phpunit
  - cp etc/wp-tests-config.php wordpress-develop/
  - sed -i "s/'DB_PASSWORD', 'dev'/'DB_PASSWORD', ''/" wordpress-develop/wp-tests-config.php
  - sed -i "s/'DB_HOST', 'db'/'DB_HOST', '127.0.0.1'/" wordpress-develop/wp-tests-config.php
  - rm -rf src/ && ln -rs ../html src
  # WP UnitTest also tests this plugin
  - curl -o wordpress-develop/wordpress-importer.zip https://downloads.wordpress.org/plugin/wordpress-importer.zip
  - unzip -d wordpress-develop/tests/phpunit/data/plugins/ wordpress-develop/wordpress-importer.zip

install:
  # Try supporting other versions
  - |
    composer require --update-with-dependencies \
    johnpbloch/wordpress:$WP_VERSION \
    phpunit/phpunit:$PHPUNIT_VERSION
  # Rerun install because downloading WordPress will overwrite plugins
  - composer install

  - cd wordpress-develop
  - npm install .
  - npm run grunt build
  - cd ..

  - vendor/bin/wp --allow-root config create --force --dbuser=travis --dbpass="" --dbhost="127.0.0.1" --skip-check
  - vendor/bin/wp --allow-root core install --skip-email
  - vendor/bin/wp --allow-root plugin activate --all

script:
  # custom tests first
  - composer validate --strict --no-check-lock --no-check-all
  # - vendor/bin/phpunit

  # WordPress tests at last
  - vendor/bin/wp --allow-root db reset --yes
  - cd wordpress-develop
  - ./phpunit

after_failure:
  - cat html/wp-content/debug.log || true
