language: php

php:
  # see http://php.net/supported-versions.php
  - '7.0' # deprecated
  - '7.1' # Until 1 Dec 2019
  - '7.2' # Until 30 Nov 2020
  - '7.3' # Until 6 Dec 2021
node_js:
  - 12.13

addons:
  apt:
    packages:
      - parallel

env:
  global:
    - PHPUNIT_VERSION="~7|~8"
    - COMPOSER_CACHE_DIR=/home/travis/.composer
    - WP_VERSION="*"
    # All jobs shall share the composer cache
    - CACHE_NAME=$TRAVIS_BRANCH
  matrix:
    # see https://codex.wordpress.org/WordPress_Versions
    # see https://phpunit.de/supported-versions.html
    - WP_VERSION=5.2.*
    # - WP_VERSION=5.1.*
    # - WP_VERSION=5.0.*
    # - WP_VERSION=4.9.*
    # - WP_VERSION=4.8.*

matrix:
  include:
    # additional combination among env (as above)
    - php: '5.6'
      env: PHPUNIT_VERSION=~5 WP_VERSION=4.9.*
    - php: '7.0'
    # Intermediate version tests due to unstable SemVer
    - php: '7.1'
      env: PHPUNIT_VERSION="~7" WP_VERSION=4.9.*
  # in the process to achieve support
  allow_failures:
    - php: '5.6'
    - php: '7.0'
    - env: WP_VERSION=dev-master
    - env: PHPUNIT_VERSION="~7"
  # Do not wait for allowed failures
  fast_finish: true

services:
  - mysql

cache:
  directories:
    - $HOME/.composer
    - $HOME/wordpress-develop/node_modules

before_install:
  - mysql -e 'CREATE DATABASE dev;'
  # Try supporting other versions
  - |
    composer require --update-with-dependencies --ignore-platform-reqs \
    johnpbloch/wordpress:$WP_VERSION \
    phpunit/phpunit:$PHPUNIT_VERSION
  # Rerun install because downloading WordPress will overwrite plugins
  - composer install --ignore-platform-reqs

install:
  - vendor/bin/wp --allow-root config create --force --dbuser=travis --dbpass="" --dbhost="127.0.0.1" --skip-check
  - cp etc/wp-tests-config.php wordpress-develop/
  - vendor/bin/wp --allow-root core install --skip-email
  - vendor/bin/wp --allow-root plugin activate --all

  # Check WordPress unit tests
  # see https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/
  - git clone --depth=1 git://develop.git.wordpress.org/ wordpress-develop
  - wget https://phar.phpunit.de/phpunit-7.5.9.phar
  - chmod +x phpunit-7.5.9.phar
  - mv phpunit-7.5.9.phar wordpress-develop/phpunit
  - cd wordpress-develop
  - npm install
  - npm run grunt build
  - ./phpunit

script:
  - composer validate --strict --no-check-lock
  # Check if platform requirements would be a problem for others
  - vendor/bin/phpunit --coverage-clover coverage.xml
  - composer install --no-dev

after_failure:
  - cat wordpress/wp-content/debug.log || true
